(() => {
  const defaultState=()=>({gold:650,food:180,gems:25,xp:0,level:1,selectedBuild:null,tiles:Array(20).fill(null),dragons:[{uid:1,type:'pyron',level:2},{uid:2,type:'tidera',level:1},{uid:3,type:'mossfang',level:1}],nextDragonId:4,eggs:[],wins:0,quests:{builder:false,collector:false,battler:false}});
  let state=SaveSystem.load()||defaultState();
  state.tiles=Array.isArray(state.tiles)?state.tiles:Array(20).fill(null);
  state.eggs=Array.isArray(state.eggs)?state.eggs:[];
  state.wins=state.wins||0;
  state.quests=state.quests||{builder:false,collector:false,battler:false};
  state.nextDragonId=state.nextDragonId||((state.dragons?.length||0)+1);
  const $=id=>document.getElementById(id);
  const ui={gold:$('goldValue'),food:$('foodValue'),gems:$('gemsValue'),level:$('levelValue'),xp:$('xpValue'),xpNeed:$('xpNeed'),xpBar:$('xpBar'),grid:$('islandGrid'),build:$('buildMenu'),dragons:$('dragonList'),dragonCount:$('dragonCount'),status:$('statusMessage'),eggCount:$('eggCount'),eggList:$('eggList'),breedA:$('breedA'),breedB:$('breedB'),battlePreview:$('battlePreview'),questList:$('questList')};
  function persist(){SaveSystem.save(state)}
  function message(text){ui.status.textContent=text}
  function dragonInfo(d){return DRAGON_DATA.find(x=>x.id===d.type)}
  function hasBuilding(type){return state.tiles.includes(type)}
  function dragonPower(d){const info=dragonInfo(d);return info.basePower+d.level*5}
  function renderResources(){ui.gold.textContent=state.gold;ui.food.textContent=state.food;ui.gems.textContent=state.gems;ui.level.textContent=state.level;const need=Economy.levelNeed(state.level);ui.xp.textContent=state.xp;ui.xpNeed.textContent=need;ui.xpBar.style.width=Math.min(100,state.xp/need*100)+'%'}
  function renderBuildMenu(){ui.build.innerHTML='';Object.entries(Economy.buildings).forEach(([key,b])=>{const btn=document.createElement('button');btn.className='build-card'+(state.selectedBuild===key?' selected':'');btn.innerHTML=`<strong>${b.art} ${b.name}</strong><span>${b.cost} gold</span>`;btn.onclick=()=>{state.selectedBuild=key;renderBuildMenu();message(`${b.name} selected. Choose an empty tile.`)};ui.build.appendChild(btn)})}
  function renderIsland(){ui.grid.innerHTML='';state.tiles.forEach((type,index)=>{const btn=document.createElement('button');btn.className='tile'+(!type?' empty':'');if(type){const b=Economy.buildings[type];btn.innerHTML=`<div class="art">${b.art}</div><div class="name">${b.name}</div>`}else{btn.innerHTML='<div class="art">＋</div><div class="name">Empty plot</div>'}btn.onclick=()=>{if(type){message(Economy.buildings[type].name);return}if(!state.selectedBuild){message('Choose a building first.');return}const result=IslandSystem.place(state,index,state.selectedBuild);if(result.ok){state.selectedBuild=null;Economy.gainXP(state,10)}message(result.msg);persist();render()};ui.grid.appendChild(btn)})}
  function renderDragons(){ui.dragons.innerHTML='';ui.dragonCount.textContent=state.dragons.length;if(!state.dragons.length){ui.dragons.innerHTML='<div class="empty-state">No dragons yet.</div>';return}state.dragons.forEach(d=>{const info=dragonInfo(d);const card=document.createElement('article');card.className='dragon-card';const cost=d.level*20;card.innerHTML=`<div class="dragon-emblem">${info.mark}</div><div class="dragon-meta"><strong>${info.name}</strong><span>${info.elements.join(' / ')} · ${info.rarity}</span><span>Level ${d.level} · Power ${dragonPower(d)}</span></div>`;const feed=document.createElement('button');feed.textContent=`Feed · ${cost} food`;feed.onclick=()=>{if(state.food<cost){message('Not enough food.');return}state.food-=cost;d.level++;Economy.gainXP(state,10);message(`${info.name} reached level ${d.level}.`);persist();render()};card.appendChild(feed);ui.dragons.appendChild(card)})}
  function renderEggs(){ui.eggCount.textContent=state.eggs.length;ui.eggList.innerHTML=state.eggs.length?state.eggs.map((e,i)=>`<div class="mini-item"><strong>Egg ${i+1}</strong><span>Mystery dragon waiting to hatch</span></div>`).join(''):'<div class="empty-state">No eggs in the hatchery.</div>'}
  function renderBreeding(){const opts=state.dragons.map(d=>{const i=dragonInfo(d);return `<option value="${d.uid}">${i.name} Lv.${d.level}</option>`}).join('');ui.breedA.innerHTML=opts;ui.breedB.innerHTML=opts}
  function renderBattle(){const team=[...state.dragons].sort((a,b)=>dragonPower(b)-dragonPower(a)).slice(0,3);const power=team.reduce((s,d)=>s+dragonPower(d),0);ui.battlePreview.innerHTML=`<div><strong>Your team power</strong><span>${power}</span></div><div><strong>Arena wins</strong><span>${state.wins}</span></div>`}
  function claimQuest(key,reward,msg){if(state.quests[key])return;state.quests[key]=true;state.gems+=reward;Economy.gainXP(state,30);message(msg);persist();render()}
  function renderQuests(){const built=state.tiles.filter(Boolean).length;const quests=[{k:'builder',title:'Realm Builder',done:built>=5,text:`Build 5 structures (${Math.min(built,5)}/5)`,reward:5},{k:'collector',title:'Dragon Keeper',done:state.dragons.length>=5,text:`Own 5 dragons (${Math.min(state.dragons.length,5)}/5)`,reward:5},{k:'battler',title:'Arena Rookie',done:state.wins>=1,text:`Win 1 battle (${Math.min(state.wins,1)}/1)`,reward:7}];ui.questList.innerHTML='';quests.forEach(q=>{const row=document.createElement('div');row.className='quest-item';row.innerHTML=`<div><strong>${q.title}</strong><span>${q.text}</span></div><button ${!q.done||state.quests[q.k]?'disabled':''}>${state.quests[q.k]?'Claimed':`Claim ${q.reward} Gems`}</button>`;row.querySelector('button').onclick=()=>claimQuest(q.k,q.reward,`${q.title} completed! +${q.reward} gems.`);ui.questList.appendChild(row)})}
  function render(){renderResources();renderBuildMenu();renderIsland();renderDragons();renderEggs();renderBreeding();renderBattle();renderQuests()}
  $('collectGoldBtn').onclick=()=>{const r=IslandSystem.collectGold(state);message(r.msg);persist();render()};
  $('harvestBtn').onclick=()=>{const r=IslandSystem.harvest(state);message(r.msg);persist();render()};
  $('buyEggBtn').onclick=()=>{if(!hasBuilding('hatchery')){message('Build a Hatchery first.');return}if(state.gold<120){message('Not enough gold.');return}state.gold-=120;state.eggs.push({kind:'mystery'});message('Mystery egg purchased.');persist();render()};
  $('hatchBtn').onclick=()=>{if(!hasBuilding('hatchery')){message('Build a Hatchery first.');return}if(!state.eggs.length){message('No eggs to hatch.');return}state.eggs.shift();const base=DRAGON_DATA.slice(0,4);const info=base[Math.floor(Math.random()*base.length)];state.dragons.push({uid:state.nextDragonId++,type:info.id,level:1});Economy.gainXP(state,20);message(`${info.name} hatched!`);persist();render()};
  $('breedBtn').onclick=()=>{if(!hasBuilding('breeding')){message('Build a Breeding Cave first.');return}if(state.gems<5){message('Not enough gems.');return}const a=state.dragons.find(d=>d.uid==ui.breedA.value),b=state.dragons.find(d=>d.uid==ui.breedB.value);if(!a||!b||a.uid===b.uid){message('Choose two different dragons.');return}state.gems-=5;const result=BREEDING_RECIPES[`${a.type}+${b.type}`]||[a.type,b.type][Math.floor(Math.random()*2)];state.dragons.push({uid:state.nextDragonId++,type:result,level:1});Economy.gainXP(state,25);message(`${dragonInfo({type:result}).name} was bred successfully!`);persist();render()};
  $('battleBtn').onclick=()=>{if(!hasBuilding('arena')){message('Build a Battle Arena first.');return}if(state.dragons.length<3){message('You need at least 3 dragons.');return}const team=[...state.dragons].sort((a,b)=>dragonPower(b)-dragonPower(a)).slice(0,3);const power=team.reduce((s,d)=>s+dragonPower(d),0);const enemy=Math.floor(70+Math.random()*80+state.level*8);if(power+Math.random()*35>=enemy){state.wins++;state.gold+=150;state.food+=50;Economy.gainXP(state,40);message(`Arena victory! Your ${power} power defeated ${enemy}. +150 gold, +50 food.`)}else{Economy.gainXP(state,10);message(`Defeat. Your ${power} power faced ${enemy}. Train and try again.`)}persist();render()};
  $('resetBtn').onclick=()=>{if(confirm('Reset Dragon Realm and erase this local save?')){SaveSystem.clear();state=defaultState();persist();message('Save reset.');render()}};
  persist();render();message('Dragon Realm Web v2 loaded. Existing browser saves are preserved.');
})();
