(() => {
  const defaultState=()=>({gold:650,food:180,gems:25,xp:0,level:1,selectedBuild:null,tiles:Array(20).fill(null),dragons:[{uid:1,type:'pyron',level:2},{uid:2,type:'tidera',level:1},{uid:3,type:'mossfang',level:1}],nextDragonId:4,eggs:[],wins:0,quests:{builder:false,collector:false,battler:false},production:Array(20).fill(0),moveFrom:null});
  let state=SaveSystem.load()||defaultState();
  state.tiles=Array.isArray(state.tiles)?state.tiles:Array(20).fill(null); state.eggs=Array.isArray(state.eggs)?state.eggs:[]; state.wins=state.wins||0; state.quests=state.quests||{builder:false,collector:false,battler:false}; state.nextDragonId=state.nextDragonId||((state.dragons?.length||0)+1); state.production=Array.isArray(state.production)&&state.production.length===20?state.production:Array(20).fill(0); state.moveFrom=null;
  let zoom=1,moveMode=false;
  const $=id=>document.getElementById(id);
  const ui={gold:$('goldValue'),food:$('foodValue'),gems:$('gemsValue'),level:$('levelValue'),xp:$('xpValue'),xpNeed:$('xpNeed'),xpBar:$('xpBar'),grid:$('islandGrid'),viewport:$('islandViewport'),build:$('buildMenu'),dragons:$('dragonList'),dragonCount:$('dragonCount'),status:$('statusMessage'),eggCount:$('eggCount'),eggList:$('eggList'),breedA:$('breedA'),breedB:$('breedB'),battlePreview:$('battlePreview'),questList:$('questList'),zoomLabel:$('zoomLabel'),moveModeBtn:$('moveModeBtn'),dialog:$('objectDialog'),dialogTitle:$('dialogTitle'),dialogBody:$('dialogBody'),dialogActions:$('dialogActions')};
  const habitatTypes=['fire','water','nature','earth']; const cycleMs=30000, farmMs=25000, hatchMs=20000;
  function persist(){SaveSystem.save(state)} function message(t){ui.status.textContent=t} function info(d){return DRAGON_DATA.find(x=>x.id===d.type)} function hasBuilding(t){return state.tiles.includes(t)} function power(d){const i=info(d);return i.basePower+d.level*5} function now(){return Date.now()} function format(ms){const s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
  function productionDuration(type){return type==='farm'?farmMs:habitatTypes.includes(type)?cycleMs:0} function ensureTimer(i,type){if(productionDuration(type)&&!state.production[i])state.production[i]=now()+productionDuration(type)} function ready(i,type){return productionDuration(type)>0&&state.production[i]&&state.production[i]<=now()}
  function renderResources(){ui.gold.textContent=state.gold;ui.food.textContent=state.food;ui.gems.textContent=state.gems;ui.level.textContent=state.level;const need=Economy.levelNeed(state.level);ui.xp.textContent=state.xp;ui.xpNeed.textContent=need;ui.xpBar.style.width=Math.min(100,state.xp/need*100)+'%'}
  function renderBuildMenu(){ui.build.innerHTML='';Object.entries(Economy.buildings).forEach(([key,b])=>{const btn=document.createElement('button');btn.className='build-card'+(state.selectedBuild===key?' selected':'');btn.innerHTML=`<strong>${b.art} ${b.name}</strong><span>${b.cost} gold</span>`;btn.onclick=()=>{moveMode=false;state.moveFrom=null;state.selectedBuild=key;renderBuildMenu();renderIsland();message(`${b.name} selected. Tap an empty plot.`)};ui.build.appendChild(btn)})}
  function dragonSprites(type){if(!habitatTypes.includes(type))return '';const els={fire:'Fire',water:'Water',nature:'Nature',earth:'Earth'};return state.dragons.filter(d=>info(d)?.elements?.includes(els[type])).slice(0,2).map((d,n)=>`<span class="dragon-sprite ${n?'two':'one'}" title="${info(d).name}">${info(d).mark}</span>`).join('')}
  function renderIsland(){ui.grid.innerHTML='';ui.grid.style.transform=`scale(${zoom})`;ui.zoomLabel.textContent=Math.round(zoom*100)+'%';ui.moveModeBtn.classList.toggle('primary',moveMode);state.tiles.forEach((type,index)=>{if(type)ensureTimer(index,type);const btn=document.createElement('button');btn.className='tile'+(!type?' empty':'')+(state.moveFrom===index?' selected':'');if(type){const b=Economy.buildings[type],dur=productionDuration(type),isReady=ready(index,type),timer=dur?(isReady?'READY':format(state.production[index]-now())):'';btn.innerHTML=`${isReady?'<span class="ready-dot"></span>':''}<div class="art">${b.art}</div><div class="name">${b.name}</div>${timer?`<div class="timer">${timer}</div>`:''}${dragonSprites(type)}`;}else btn.innerHTML='<div class="art">＋</div><div class="name">Empty plot</div>';
      btn.onclick=()=>handleTile(index,type);ui.grid.appendChild(btn)});persist()}
  function handleTile(index,type){if(moveMode){if(type&&state.moveFrom===null){state.moveFrom=index;message('Building selected. Tap an empty plot to move it.');renderIsland();return}if(!type&&state.moveFrom!==null){state.tiles[index]=state.tiles[state.moveFrom];state.tiles[state.moveFrom]=null;state.production[index]=state.production[state.moveFrom];state.production[state.moveFrom]=0;state.moveFrom=null;persist();render();message('Building moved.');return}message('Choose a building, then an empty destination.');return}
    if(type){openBuilding(index,type);return} if(!state.selectedBuild){message('Choose a building first.');return}const selected=state.selectedBuild;const result=IslandSystem.place(state,index,selected);if(result.ok){state.selectedBuild=null;ensureTimer(index,selected);Economy.gainXP(state,10)}message(result.msg);persist();render()}
  function openBuilding(index,type){const b=Economy.buildings[type];ui.dialogTitle.textContent=b.name;ui.dialogBody.innerHTML='';ui.dialogActions.innerHTML='';const dur=productionDuration(type);const r=ready(index,type);let body=`<div class="dialog-stat"><span>Plot</span><strong>${index+1}</strong></div>`;if(dur)body+=`<div class="dialog-stat"><span>Status</span><strong>${r?'Ready to collect':format(state.production[index]-now())}</strong></div>`;if(habitatTypes.includes(type))body+=`<div class="dialog-stat"><span>Gold per cycle</span><strong>${b.gold}</strong></div>`;if(type==='farm')body+=`<div class="dialog-stat"><span>Food per harvest</span><strong>${b.food}</strong></div>`;ui.dialogBody.innerHTML=body;
    if(dur){const c=document.createElement('button');c.className='primary';c.textContent=type==='farm'?'Harvest':'Collect Gold';c.disabled=!r;c.onclick=()=>{collectTile(index,type);ui.dialog.close()};ui.dialogActions.appendChild(c)}
    const move=document.createElement('button');move.textContent='Move';move.onclick=()=>{moveMode=true;state.moveFrom=index;ui.dialog.close();renderIsland();message('Tap an empty plot to move this building.')};ui.dialogActions.appendChild(move);if(typeof ui.dialog.showModal==='function')ui.dialog.showModal()}
  function collectTile(index,type){if(!ready(index,type)){message('Production is not ready yet.');return false}if(type==='farm'){state.food+=Economy.buildings[type].food;message(`+${Economy.buildings[type].food} food harvested.`)}else{state.gold+=Economy.buildings[type].gold;message(`+${Economy.buildings[type].gold} gold collected.`)}state.production[index]=now()+productionDuration(type);Economy.gainXP(state,5);persist();render();return true}
  function collectAll(kind){let total=0;state.tiles.forEach((type,i)=>{if(!type||!ready(i,type))return;if(kind==='gold'&&habitatTypes.includes(type)){total+=Economy.buildings[type].gold;state.gold+=Economy.buildings[type].gold;state.production[i]=now()+cycleMs}else if(kind==='food'&&type==='farm'){total+=Economy.buildings[type].food;state.food+=Economy.buildings[type].food;state.production[i]=now()+farmMs}});if(total){Economy.gainXP(state,5);message(`Collected ${total} ${kind}.`)}else message(`No ${kind} production is ready yet.`);persist();render()}
  function renderDragons(){ui.dragons.innerHTML='';ui.dragonCount.textContent=state.dragons.length;state.dragons.forEach(d=>{const i=info(d),card=document.createElement('article');card.className='dragon-card';const cost=d.level*20;card.innerHTML=`<div class="dragon-emblem">${i.mark}</div><div class="dragon-meta"><strong>${i.name}</strong><span>${i.elements.join(' / ')} · ${i.rarity}</span><span>Level ${d.level} · Power ${power(d)}</span></div>`;const feed=document.createElement('button');feed.textContent=`Feed · ${cost} food`;feed.onclick=()=>{if(state.food<cost){message('Not enough food.');return}state.food-=cost;d.level++;Economy.gainXP(state,10);message(`${i.name} reached level ${d.level}.`);persist();render()};card.appendChild(feed);ui.dragons.appendChild(card)});if(!state.dragons.length)ui.dragons.innerHTML='<div class="empty-state">No dragons yet.</div>'}
  function renderEggs(){ui.eggCount.textContent=state.eggs.length;ui.eggList.innerHTML=state.eggs.length?state.eggs.map((e,i)=>`<div class="mini-item"><strong>Egg ${i+1}</strong><span>${e.hatchEnd?e.hatchEnd<=now()?'Ready to hatch!':'Incubating · '+format(e.hatchEnd-now()):'Waiting for incubation'}</span></div>`).join(''):'<div class="empty-state">No eggs in the hatchery.</div>'}
  function renderBreeding(){const opts=state.dragons.map(d=>`<option value="${d.uid}">${info(d).name} Lv.${d.level}</option>`).join('');ui.breedA.innerHTML=opts;ui.breedB.innerHTML=opts}
  function renderBattle(){const team=[...state.dragons].sort((a,b)=>power(b)-power(a)).slice(0,3),p=team.reduce((s,d)=>s+power(d),0);ui.battlePreview.innerHTML=`<div><strong>Your team power</strong><span>${p}</span></div><div><strong>Arena wins</strong><span>${state.wins}</span></div>`}
  function claimQuest(key,reward,msg){if(state.quests[key])return;state.quests[key]=true;state.gems+=reward;Economy.gainXP(state,30);message(msg);persist();render()}
  function renderQuests(){const built=state.tiles.filter(Boolean).length,qs=[{k:'builder',title:'Realm Builder',done:built>=5,text:`Build 5 structures (${Math.min(built,5)}/5)`,reward:5},{k:'collector',title:'Dragon Keeper',done:state.dragons.length>=5,text:`Own 5 dragons (${Math.min(state.dragons.length,5)}/5)`,reward:5},{k:'battler',title:'Arena Rookie',done:state.wins>=1,text:`Win 1 battle (${Math.min(state.wins,1)}/1)`,reward:7}];ui.questList.innerHTML='';qs.forEach(q=>{const row=document.createElement('div');row.className='quest-item';row.innerHTML=`<div><strong>${q.title}</strong><span>${q.text}</span></div><button ${!q.done||state.quests[q.k]?'disabled':''}>${state.quests[q.k]?'Claimed':`Claim ${q.reward} Gems`}</button>`;row.querySelector('button').onclick=()=>claimQuest(q.k,q.reward,`${q.title} completed! +${q.reward} gems.`);ui.questList.appendChild(row)})}
  function render(){renderResources();renderBuildMenu();renderIsland();renderDragons();renderEggs();renderBreeding();renderBattle();renderQuests()}
  $('collectGoldBtn').onclick=()=>collectAll('gold'); $('harvestBtn').onclick=()=>collectAll('food'); $('zoomInBtn').onclick=()=>{zoom=Math.min(1.35,zoom+.1);renderIsland()}; $('zoomOutBtn').onclick=()=>{zoom=Math.max(.75,zoom-.1);renderIsland()}; ui.moveModeBtn.onclick=()=>{moveMode=!moveMode;state.moveFrom=null;state.selectedBuild=null;render();message(moveMode?'Move mode: tap a building, then an empty plot.':'Move mode off.')}; $('dialogCloseBtn').onclick=()=>ui.dialog.close();
  $('buyEggBtn').onclick=()=>{if(!hasBuilding('hatchery'))return message('Build a Hatchery first.');if(state.gold<120)return message('Not enough gold.');state.gold-=120;state.eggs.push({kind:'mystery',hatchEnd:0});message('Mystery egg purchased.');persist();render()};
  $('hatchBtn').onclick=()=>{if(!hasBuilding('hatchery'))return message('Build a Hatchery first.');if(!state.eggs.length)return message('No eggs to hatch.');const e=state.eggs[0];if(!e.hatchEnd){e.hatchEnd=now()+hatchMs;message('Incubation started. Come back when the timer finishes.');persist();render();return}if(e.hatchEnd>now())return message(`Egg still incubating: ${format(e.hatchEnd-now())}.`);state.eggs.shift();const base=DRAGON_DATA.slice(0,4),d=base[Math.floor(Math.random()*base.length)];state.dragons.push({uid:state.nextDragonId++,type:d.id,level:1});Economy.gainXP(state,20);message(`${d.name} hatched!`);persist();render()};
  $('breedBtn').onclick=()=>{if(!hasBuilding('breeding'))return message('Build a Breeding Cave first.');if(state.gems<5)return message('Not enough gems.');const a=state.dragons.find(d=>d.uid==ui.breedA.value),b=state.dragons.find(d=>d.uid==ui.breedB.value);if(!a||!b||a.uid===b.uid)return message('Choose two different dragons.');state.gems-=5;const result=BREEDING_RECIPES[`${a.type}+${b.type}`]||[a.type,b.type][Math.floor(Math.random()*2)];state.eggs.push({kind:result,hatchEnd:0});Economy.gainXP(state,25);message(`Breeding created a new egg. Move it through the Hatchery.`);persist();render()};
  $('battleBtn').onclick=()=>{if(!hasBuilding('arena'))return message('Build a Battle Arena first.');if(state.dragons.length<3)return message('You need at least 3 dragons.');const team=[...state.dragons].sort((a,b)=>power(b)-power(a)).slice(0,3),p=team.reduce((s,d)=>s+power(d),0),enemy=Math.floor(70+Math.random()*80+state.level*8);if(p+Math.random()*35>=enemy){state.wins++;state.gold+=150;state.food+=50;Economy.gainXP(state,40);message(`Arena victory! ${p} vs ${enemy}. +150 gold, +50 food.`)}else{Economy.gainXP(state,10);message(`Defeat. ${p} vs ${enemy}. Train and try again.`)}persist();render()};
  $('resetBtn').onclick=()=>{if(confirm('Reset Dragon Realm and erase this local save?')){SaveSystem.clear();state=defaultState();persist();render();message('Save reset.')}};
  setInterval(()=>{renderIsland();renderEggs()},1000);persist();render();message('Interactive Web v3 loaded. Tap buildings, watch timers, move structures, and manage the island directly.');
})();
