(() => {
  const defaultState=()=>({gold:650,food:180,gems:25,xp:0,level:1,selectedBuild:null,tiles:Array(20).fill(null),dragons:[{uid:1,type:'pyron',level:2},{uid:2,type:'tidera',level:1},{uid:3,type:'mossfang',level:1}],nextDragonId:4});
  let state=SaveSystem.load()||defaultState();
  const $=id=>document.getElementById(id);
  const ui={gold:$('goldValue'),food:$('foodValue'),gems:$('gemsValue'),level:$('levelValue'),xp:$('xpValue'),xpNeed:$('xpNeed'),xpBar:$('xpBar'),grid:$('islandGrid'),build:$('buildMenu'),dragons:$('dragonList'),dragonCount:$('dragonCount'),status:$('statusMessage')};
  function persist(){SaveSystem.save(state)}
  function message(text){ui.status.textContent=text}
  function dragonInfo(d){return DRAGON_DATA.find(x=>x.id===d.type)}
  function renderResources(){ui.gold.textContent=state.gold;ui.food.textContent=state.food;ui.gems.textContent=state.gems;ui.level.textContent=state.level;const need=Economy.levelNeed(state.level);ui.xp.textContent=state.xp;ui.xpNeed.textContent=need;ui.xpBar.style.width=Math.min(100,state.xp/need*100)+'%'}
  function renderBuildMenu(){ui.build.innerHTML='';Object.entries(Economy.buildings).forEach(([key,b])=>{const btn=document.createElement('button');btn.className='build-card'+(state.selectedBuild===key?' selected':'');btn.innerHTML=`<strong>${b.art} ${b.name}</strong><span>${b.cost} gold</span>`;btn.addEventListener('click',()=>{state.selectedBuild=key;renderBuildMenu();message(`${b.name} selected. Choose an empty tile.`)});ui.build.appendChild(btn)})}
  function renderIsland(){ui.grid.innerHTML='';state.tiles.forEach((type,index)=>{const btn=document.createElement('button');btn.className='tile'+(!type?' empty':'');if(type){const b=Economy.buildings[type];btn.innerHTML=`<div class="art">${b.art}</div><div class="name">${b.name}</div>`}else{btn.innerHTML='<div class="art">＋</div><div class="name">Empty plot</div>'}btn.addEventListener('click',()=>{if(type){message(Economy.buildings[type].name);return}if(!state.selectedBuild){message('Choose a building first.');return}const result=IslandSystem.place(state,index,state.selectedBuild);if(result.ok)state.selectedBuild=null;message(result.msg);persist();render()});ui.grid.appendChild(btn)})}
  function renderDragons(){ui.dragons.innerHTML='';ui.dragonCount.textContent=state.dragons.length;if(!state.dragons.length){ui.dragons.innerHTML='<div class="empty-state">No dragons yet.</div>';return}state.dragons.forEach(d=>{const info=dragonInfo(d);const card=document.createElement('article');card.className='dragon-card';const cost=d.level*20;const power=info.basePower+d.level*5;card.innerHTML=`<div class="dragon-emblem">${info.mark}</div><div class="dragon-meta"><strong>${info.name}</strong><span>${info.element} · Level ${d.level}</span><span>Power ${power}</span></div>`;const feed=document.createElement('button');feed.textContent=`Feed · ${cost} food`;feed.addEventListener('click',()=>{if(state.food<cost){message('Not enough food.');return}state.food-=cost;d.level++;Economy.gainXP(state,10);message(`${info.name} reached level ${d.level}.`);persist();render()});card.appendChild(feed);ui.dragons.appendChild(card)})}
  function render(){renderResources();renderBuildMenu();renderIsland();renderDragons()}
  $('collectGoldBtn').addEventListener('click',()=>{const r=IslandSystem.collectGold(state);message(r.msg);persist();render()});
  $('harvestBtn').addEventListener('click',()=>{const r=IslandSystem.harvest(state);message(r.msg);persist();render()});
  $('resetBtn').addEventListener('click',()=>{if(confirm('Reset Dragon Realm and erase this local save?')){SaveSystem.clear();state=defaultState();persist();message('Save reset.');render()}});
  if(!SaveSystem.load())persist();render();message('Stable Web v1 loaded. Your progress saves automatically in this browser.');
})();
